project:
  type: website

website:
  title: "Coverage Tracker"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: Point_Coverage.html
        text: Point Datasets
      - href: Polygon_Coverage.html
        text: Polygon Coverage

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

